### PR TITLE
addition of delta

### PR DESCRIPTION
**Pull request by emburkino**
The FIRE documentation for CDS Index and Single name should be updated to include the field "delta" as this used to determine the position long typically delta '-1' or short '1'. Both of the JSON files are short in this case.

### CODE REVIEW

**Comment by muratabur** [comment]
@seelan93 could you give your review as well? I would have thought short would be -1 and not +1?

**Comment by seelan93** [comment]
> @seelan93 could you give your review as well? I would have thought short would be -1 and not +1?

Yes you are right, I wonder if there has been some confusion here due to how Market risk handles CDS

- Positive delta represents bought protection and negative represents sold protection
- For the derivation of notional positions to be used in IR market risk calculation - sold protection would actually be represented as a synthetic long position and vice versa for bought protection which is maybe where this has come from @emburkino ?
- Can look at Art 332 CRR for more details on this

We handle the derivation of notional positions in the logic so there would be no need to have -1 to represent long etc in the actual mapping

We should change this to -1

**Comment by emburkino** [comment]
I will change it to -1. Yes, @seelan93 the issue https://gitlab.internal.suade.org/suade/Services/-/issues/14385 suggests having short at 1 and long at -1 which is most likely due to this 'the derivation of notional positions to be used in IR market risk calculation - sold protection would actually be represented as a synthetic long position and vice versa for bought protection .'

**Comment by muratabur** [comment]
ready to merge @seelan93 @emburkino ?

**Pull request merged**
