### PR TITLE
Add fields for calculating the HQLA. Add interest_repayment_frequency…

### PR DESCRIPTION
**Pull request by enzocc**
… to accounts

### CODE REVIEW

**Review by muratabur — CHANGES_REQUESTED** [review]
**value_change**:

Is this referring to LCR Article 12 (c) (iii)? because that is more about the max loss or change in a 30day stress window and not the last 30days (ie. how did this stock behave in september 2008?) If that is the case, we should be more clear in the description and maybe the attribute name (eg. stress_haircut).

> Art. 12 ... they have a proven record  as a reliable source of liquidity at all times, including during stress  periods. This requirement shall be deemed met where the level of decline  in the share's stock price or increase in its haircut during a 30 day  calendar day market stress period did not exceed 40 % or 40 percentage  points, respectively; and





**maturity**: 

Can we call this "issue_maturity* to align it with "issue_size" and avoid it being confused with original or residual maturity.

**status**:

If we are adding non-op here, does this mean we can drop it from the hqla classes?

**Comment by enzocc** [comment]
**maturity:**
I was trying to highlight a difference between the size of the issue and the maturity of the bond (I don't think a issue has a maturity), but we could standardise the names.

**status**
That is correct, we should get rid of it. In fact back when we added the non-op HQLA's the original proposal was to add a flag, rather to change the Enum, so we would be going back to that proposal.

However, we can't phase this out yet, as several banks are using the Enums already. I propose not to mix Merge Requests and send a proper warning to everyone.

Something to be careful about is to avoid having the "status" field becoming a default bucket for anything that may require a new  flag. My preference is still having the operational / non_operational on it's own enum / flag.

i.e. Is there any potential intersection between paid_up, called_up, bankruptcy_remote and non_operational?

**value change**
There are two separate things on that article:
- the level of decline in the share's stock price -> Measured in percentage.
- the level of increase in it's haircut -> Measured in basis points.

The value change captures the first bullet point. What do you think about stress_value_change?. At the moment the attribute captures increase or decline to make it more generic.
We can potentially add a stress_haircut_change as well to cover both cases. What do you think?

**Comment by muratabur** [comment]
**maturity**
So bond and issue are used interchangeably. The issue is the whole 100mn issuance for example and a bond will be like a $100 chunk, so there will be 1mn bonds issued. So technically the issue is the one with the maturity, not the bond.

**status**
It is not good to have boolean fields/flags/enums because it leads to potential conflicts. For example what if level one hqla needs to always be operational? In a tree you can remove the possibility of bad data, but with flags you can't.
For the cases you mentioned and intersections, I think it is OK because they refer to very different use cases (ie. share capital, securities deposited with a CCP somewhere and securities held on balance sheet). We can always extend the tree if we need to accommodate 2 of those in conjunction.

**value_change**
The way I was reading the Article, it is asking the firm to make a judgement call on how the security holds up in periods of stress and then it suggests considering the maximum 30-day decline (typically a suitable metric for equities) or the change in haircut (typically a suitable metric for bonds) in a historical stress scenario (like sep 2008). So I think it is just one number but depending on the type of security you will need to use on or the other. How about **stress_change** as a percent?

**Comment by enzocc** [comment]
**maturity**
ok

**status**
agreed about the boolean vs enums.

**value change**

From the article, it's clear that the regulator is giving both options (price or haircuts) for shares. This means that potentially you could have an institution looking at the haircut increase for a share. Strange?

Perhaps we can use the signs? When it's negative, we know that is a decrease and so we assume that its a decrease in price. When it's positive, we know that it is an increase and so we assume that it is an increase in haircut.

Obvious drawbacks is that if we won't be able to capture an increase in price or a decrease in haircut (are those metrics even useful?)

image

**Comment by muratabur** [comment]
Ah I didn't see they both relate to shares. Let's not use the sign as it could be confusing. I don't think we need to know whether the metric So we can think of this attribute as:

= max(price move, haircut) in a 30d stress period

I guess what this is really trying to measure is "gap risk" - how much can the stock fall without you being able to get rid of it.
So we wont know if it is price move or haircut being used. But do we need to know?

**Comment by enzocc** [comment]
Well, the way I am reading this is that the bank could flag an increase in haircut in basis points, or a decrease in price in percentage. If they send us 150bp (1.5%) and without signs, how do we know if they refer to a haircut increase or a price decrease? If we will just mix both, we might as well put a flag, which I know we hate :)

**Comment by muratabur** [comment]
Well I am saying I don't think it is necessary to know which metric (change in market price or change in haircut) they are using. It is also not known which 30-day period (or crisis) is being used for the determination.

Either the repo haircut jumps by 40% or the price drops by 40%, either way, you just want to see if the gap risk is > 40%, regardless of how gap risk is determined.

**Comment by enzocc** [comment]
Great! I was completely misreading the articles. I made the ammendments

**Review by muratabur — APPROVED** [review]

**Pull request merged**
