### PR TITLE
change json schema version from draft-04 to draft-06

### PR DESCRIPTION
**Pull request by habospace**
Ran a draft-06 validator on all our json schema files and they all look fine (so we're not using any draft-04 features that are incompatible with draft-06).

### CODE REVIEW

**Comment by olliemath** [comment]
Actually, should we just go straight to v7 (the latest)?

**Comment by muratabur** [comment]
@habospace any reason to not go to latest (v7)?

**Comment by olliemath** [comment]
(also note: we cannot merge this until we support v6/7 internally)

**Comment by habospace** [comment]
sure we can go to v7, will update the PR shortly

**Comment by habospace** [comment]
moved this to: https://github.com/SuadeLabs/fire/pull/216

**Pull request closed without merging**
