### PR TITLE
366 new attrs for osfi reports bd and bb

### PR DESCRIPTION
**Pull request by emburkino**
New attributes on the Loan and Account schemas to accommodate for the OSFI data requirement for reports BB and BD

Attributes as follows:
- Economic Loss
- Fraud Loss

### CODE REVIEW

**Comment by muratabur** [comment]
@emburkino did we add these to the JSON schema as well?

**Comment by emburkino** [comment]
> @emburkino did we add these to the JSON schema as well?

Updated now

**Comment by muratabur** [comment]
Hey @emburkino we don't want to add more exceptions to the schemas tests, can you change the economic_loss enums to econ_loss...  so they are shorter and we don't have to modify the tests

Thanks

**Comment by muratabur** [comment]
great @emburkino  and extra points for sorting the enums in the documentation (+1)

**Pull request merged**
