### PR TITLE
feat(security): add collateralization ratio attribute

### PR DESCRIPTION
**Pull request by albieduffy**

### CODE REVIEW

**Comment by muratabur** [comment]
hi @albieduffy is this ratio a percentage of balance, mtm or notional amount or something else?

**Comment by albieduffy** [comment]
@muratabur 
> hi @albieduffy is this ratio a percentage of balance, mtm or notional amount or something else?

Overcollateralisation is based on the covered pool balance/issuance size.

For example, the below extract comes from a HSBC Covered Bond Investor Report

image (2)

For example, the below extract comes from a CBS Covered Bond Investor Report

image (3)

**Comment by muratabur** [comment]
Hey, so, I guess, would it make more sense to add the "cover pool balance" and deduce the ratio?

This would make doing some things easier like aggregating, comparing total principal amount outstanding across all covered bonds to total cover pool balance

**Comment by albieduffy** [comment]
@muratabur makes sense, I'll update this MR to cover pool balance and that with issue size can be used to deduce the ratio

**Pull request merged**
