### PR TITLE
205 other fs fees

### PR DESCRIPTION
**Pull request by anh-suade**
New amount field added for proper calculation of current ltv for loans.  Without this input, current ltv will be incorrectly calculated and arrive at incorrect risk weight calculations.

### CODE REVIEW

**Comment by muratabur** [comment]
Is there more guidance on what these fees should include?

**Comment by anh-suade** [comment]
Got the definition from the client for other_fs_fee.  It references chapter 4, P92.  They define it as "The amount from pledged deposit accounts with the lending institution that meet requirements for on-balance sheet netting and have been unconditionally and irrevocably pledged for the sole purpose of redemption of the mortgage loan".   

Ref:  Chapter 4 P92
"When calculating the LTV ratio, the loan amount will be reduced as the loan amortises. The LTV ratio should be re-calculated upon any refinancing, and whenever deemed prudent. The LTV ratio must be prudently calculated in accordance with the following requirements:

Amount of the loan: includes the outstanding loan amount and any undrawn committed amount of the mortgage loan. The loan amount must be calculated gross of any provisions and other risk mitigants, **except for pledged deposits accounts with the lending institution that meet all requirements for on-balance sheet netting and have been unconditionally and irrevocably pledged for the sole purposes of redemption of the mortgage loan.**

**Comment by samir-dahmani** [comment]
The client came back on the previous clarification. This attribute should be used to record sundries that are due on the loan. These sundries will be used to calculate the ltv of the loan

**Comment by muratabur** [comment]
added via another branch

**Pull request closed without merging**
