### PR TITLE
Implement reporter schema.

### PR DESCRIPTION
**Pull request by Pavlov123**

### CODE REVIEW

**Comment by Pavlov123** [comment]
So this is failing because the tests check refs only against common.json. Is this on purpose?

**Comment by olliemath** [comment]
Hmm, I don't think it is deliberate, just an implementation detail of the test. The *real* requirement is that all refs should point to a file in this repo (so that an air-gapped system could theoretically resolve the refs without making external web requests)

**Comment by muratabur** [comment]
@Pavlov123 why don't we just have this schema inherit from entity like the customer schema?

**Comment by Pavlov123** [comment]
@muratabur Just to not have the other fields in the entity schema since they are not relevant to our current use case. If you guys think that they would be though we can definitely do that.

**Pull request merged**
