### PR TITLE
Add main index boolean

### PR DESCRIPTION
**Pull request by suadkw**
added field main index

### CODE REVIEW

**Review by muratabur — COMMENTED** [review]
Hey, do we need this? Can't you just check `product_name` and `mic_code` that should have an index name that matches the lists given in that regulation.

**Comment by suadkw** [comment]
> Hey, do we need this? Can't you just check `product_name` and `mic_code` that should have an index name that matches the lists given in that regulation.

I think you are correct. We have attempted a different implementation via credit risk helpers. Thank you for your input.

**Comment by muratabur** [comment]
cool cool, ok to kill this then?

**Comment by suadkw** [comment]
not just yet... it seems as if the client might prefer an implementation where we include this boolean

**Comment by muratabur** [comment]
Let's not confuse a software implementation with FIRE...

Conflict with `mic_code` is a violation of the [principle of consistency](https://github.com/SuadeLabs/fire/blob/master/guiding_principles.md#schema-design-principles).

**Pull request closed without merging**
